openapi: 3.0.1
info:
  title: Customer Service API
  version: 1.0.0
  description: Customer management microservice for bank system.

servers:
  - url: http://localhost:8081

paths:

  /:
    get:
      summary: Get all customers
      tags: [Customer]
      responses:
        "200":
          description: Customer list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"

    post:
      summary: Create a new customer
      tags: [Customer]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerRequest"
      responses:
        "201":
          description: Customer created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"

  /{id}:
    get:
      summary: Get a customer by ID
      tags: [Customer]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Customer found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        "404":
          description: Customer not found

    put:
      summary: Update a customer
      tags: [Customer]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerRequest"
      responses:
        "200":
          description: Customer updated

    delete:
      summary: Delete customer
      tags: [Customer]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "204":
          description: Customer deleted


components:
  schemas:

    Customer:
      type: object
      required: [id, type, documentType, documentNumber, fullname]
      properties:
        id:
          type: string
        type:
          type: string
          enum: [PERSONAL, BUSINESS]
        documentType:
          type: string
        documentNumber:
          type: string
        fullname:
          type: string
        email:
          type: string
        phone:
          type: string

    CustomerRequest:
      type: object
      required: [type, documentType, documentNumber, fullname]
      properties:
        type:
          type: string
          enum: [PERSONAL, BUSINESS]
        documentType:
          type: string
        documentNumber:
          type: string
        fullname:
          type: string
        email:
          type: string
        phone:
          type: string